// <auto-generated />
using HighscoreBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HighscoreBackend.Migrations
{
    [DbContext(typeof(HighscoreDBContext))]
    [Migration("20200325164704_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.2.20120.8");

            modelBuilder.Entity("HighscoreBackend.Model.Highscore", b =>
                {
                    b.Property<int>("HighscoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("HighscoreID");

                    b.ToTable("Highscore");
                });
#pragma warning restore 612, 618
        }
    }
}
